import { Area } from '../model/area';
import { Demografi } from '../model/demografi';
import { Gender } from '../model/gender';
import { Organisation } from '../model/organisation';
import { WebSite } from '../model/site';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable()
export class SiteService {

  private webSites: WebSite[] = [
    new WebSite(
      'Gundmann',
      'http://www.gundmann.dk',
      true,
      new Demografi(Gender.Unisex),
      new Area('2720', 'Denmark'),
      new Organisation('Sunhed')
    ),
    new WebSite(
      'adscoop',
      'http://www.ad-scoop.dk',
      true,
      new Demografi(Gender.Man),
      new Area('2720', 'Denmark'),
      new Organisation('Forening')),
    new WebSite(
      'Hansen',
      'http://www.hansen.dk',
      false,
      new Demografi(Gender.Woman),
      new Area('2720', 'Denmark'),
      new Organisation('Frisør')),
    new WebSite(
      'VIF',
      'http://www.vif.dk',
      true,
      new Demografi(Gender.Unisex),
      new Area('2720', 'Denmark'),
      new Organisation('Forening')),
    new WebSite(
      'Amager',
      'http://www.amager.dk',
      true,
      new Demografi(Gender.Unisex),
      new Area('2720', 'Denmark'),
      new Organisation('Købmand'))
  ];

  countries: string[] = [
    'Afghanistan',
    'Albanien',
    'Algeriet',
    'Andorra',
    'Angola',
    'Antigua &Barbuda',
    'Argentina',
    'Armenien',
    'Aserbajdsjan',
    'Australien',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belgien',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnien-Herzegovina',
    'Botswana',
    'Brasilien',
    'Brunei',
    'Bulgarien',
    'Burkina Faso',
    'Burma (Myanmar)',
    'Burundi',
    'Cambodja',
    'Cameroun',
    'Canada',
    'Centralafrika',
    'Chad',
    'Chile',
    'Colombia',
    'Comorerne',
    'Congo',
    'Costa Rica',
    'Cuba',
    'Cypern',
    'Darussalem',
    'Demokratiske rep. Congo',
    'Djibouti',
    'Dominica',
    'Dominikanske Republik',
    'Ecuador',
    'Egypten',
    'El Salvador',
    'Elfenbens-kysten',
    'Eritrea',
    'Estland',
    'Etiopien',
    'Fiji',
    'Filippinerne',
    'Finland',
    'Forenede Arab. Emirater',
    'Frankrig',
    'Gabon',
    'Gambia',
    'Georgien',
    'Ghana',
    'Grenada',
    'Grenadinerne',
    'Grækenland',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hviderusland (Belarus)',
    'Indien',
    'Indonesien',
    'Irak',
    'Iran',
    'Irland',
    'Island',
    'Israel',
    'Italien',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kapverdiske Øer',
    'Kasakhstan',
    'Kenya',
    'Kina',
    'Kirgisistan',
    'Kiribati',
    'Kroatien',
    'Kuwait',
    'Laos',
    'Lesotho',
    'Letland',
    'Libanon',
    'Liberia',
    'Libyen',
    'Liechtenstein',
    'Litauen',
    'Luxembourg',
    'Madagaskar',
    'Makedonien (FYROM)',
    'Malawi',
    'Malaysia',
    'Maldiverne',
    'Mali',
    'Malta',
    'Marokko',
    'Marshall-øerne',
    'Mauretanien',
    'Mauritius',
    'Mexico',
    'Mikronesien',
    'Moldova',
    'Monaco',
    'Mongoliet',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nederlandene',
    'Nepal',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Nordkorea',
    'Norge',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestina',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Polen',
    'Portugal',
    'Qatar',
    'Rumænien',
    'Rusland',
    'Rwanda',
    'Salomonøerne',
    'Samoa',
    'San Marino',
    'Sao Tomé & Principe',
    'Saudi Arabien',
    'Schweiz',
    'Senegal',
    'Serbien og Montenegro',
    'Seychellerne',
    'Sierra Leone',
    'Singapore',
    'Slovakiet',
    'Slovenien',
    'Somalia',
    'Spanien',
    'Sri Lanka',
    'St. Kitts-Nevis',
    'St. Lucia',
    'St. Vincent',
    'Storbritannien',
    'Sudan',
    'Surinam',
    'Sverige',
    'Swaziland',
    'Sydafrika',
    'Sydkorea',
    'Syrien',
    'Tadjikistan',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Tjekkiet',
    'Togo',
    'Tonga',
    'Trinidad & Tobago',
    'Tunesien',
    'Turkmenistan',
    'Tuvalu',
    'Tyrkiet',
    'Tyskland',
    'Uganda',
    'Ukraine',
    'Ungarn',
    'Uruguay',
    'USA',
    'Usbekistan',
    'Vanuatu',
    'Vatikanet',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Ækvatorial Guinea',
    'Østrig',
    'Østtimor'
  ];

  constructor() { }

  public sites(): Observable<WebSite[]> {
    return Observable.of(this.webSites);
  }

  public add(webSite: WebSite): Observable<boolean> {
    this.webSites.push(webSite);
    return Observable.of(true);
  }

  public edit(webSite: WebSite): Observable<boolean> {
    return Observable.of(true);
  }

}
